### ISSUE TITLE
Login de usuario

### ISSUE THREAD

**Issue by profealejandroduoc** [profealejandroduoc/proyectoGHY2024#12]
Como `Usuario del sistema`
Necesito `iniciar sesión `
Para `Poder acceder a mi perfil y mis funcionalidades`

Precondiciones:
*El Usuario debe estar creado en la base de datos*

Criterios de Aceptación
- [ ] El usuario accede al sistema
- [ ]  El usuario pude acceder a su perfil

**Comment by javegaf** [comment]
¿Cuándo pagan?
